version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: shopify-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shopify_store
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: shopify-redis
    restart: always
    ports:
      - '6379:6379'

  sonarqube:
    image: sonarqube:latest
    container_name: shopify-sonarqube
    restart: always
    ports:
      - '9000:9000'

volumes:
  mysql_data:
