module.exports = () => [
  {
    type: 'checkbox',
    id: 'highlight',
    label: 'Highlight tile',
    info: 'A highlighted tile takes bigger space. Only has effect on desktop. Do not highlight more than 1 item per row.',
    default: false,
  },
  {
    type: 'text',
    id: 'subheading',
    label: 'Subheading',
    default: 'Featured',
  },
  {
    type: 'product',
    id: 'product_1',
    label: 'Product 1',
  },
  {
    type: 'image_picker',
    id: 'product_image_1',
    label: 'Use instead of the product image',
    info: '1800 x 900px .jpg recommended',
  },
  {
    type: 'checkbox',
    id: 'product_full_content_1',
    label: 'Full product content',
    info: 'Full content may include some additional features like hover buttons, size selectors etc.',
    default: false,
  },
  {
    type: 'text',
    id: 'product_image_desk_ratio_1',
    label: '[Desktop] Product 1 image ratio',
    info: 'If set overrides desktop image ratio',
  },
  {
    type: 'text',
    id: 'product_image_mobile_ratio_1',
    label: '[Mobile] Product 1 image ratio',
    info: 'If set overrides mobile image ratio',
  },
  {
    type: 'product',
    id: 'product_2',
    label: 'Product 2',
  },
  {
    type: 'image_picker',
    id: 'product_image_2',
    label: 'Use instead of the product image',
    info: '1800 x 900px .jpg recommended',
  },
  {
    type: 'checkbox',
    id: 'product_full_content_2',
    label: 'Full product content',
    info: 'Full content may include some additional features like hover buttons, size selectors etc.',
    default: false,
  },
  {
    type: 'text',
    id: 'product_image_desk_ratio_2',
    label: '[Desktop] Product 2 image ratio',
    info: 'If set overrides desktop image ratio',
  },
  {
    type: 'text',
    id: 'product_image_mobile_ratio_2',
    label: '[Mobile] Product 2 image ratio',
    info: 'If set overrides mobile image ratio',
  },
  {
    type: 'product',
    id: 'product_3',
    label: 'Product 3',
  },
  {
    type: 'image_picker',
    id: 'product_image_3',
    label: 'Use instead of the product image',
    info: '1800 x 900px .jpg recommended',
  },
  {
    type: 'checkbox',
    id: 'product_full_content_3',
    label: 'Full product content',
    info: 'Full content may include some additional features like hover buttons, size selectors etc.',
    default: false,
  },
  {
    type: 'text',
    id: 'product_image_desk_ratio_3',
    label: '[Desktop] Product 3 image ratio',
    info: 'If set overrides desktop image ratio',
  },
  {
    type: 'text',
    id: 'product_image_mobile_ratio_3',
    label: '[Mobile] Product 3 image ratio',
    info: 'If set overrides mobile image ratio',
  },
  {
    type: 'product',
    id: 'product_4',
    label: 'Product 4',
  },
  {
    type: 'image_picker',
    id: 'product_image_4',
    label: 'Use instead of the product image',
    info: '1800 x 900px .jpg recommended',
  },
  {
    type: 'checkbox',
    id: 'product_full_content_4',
    label: 'Full product content',
    info: 'Full content may include some additional features like hover buttons, size selectors etc.',
    default: false,
  },
  {
    type: 'text',
    id: 'product_image_desk_ratio_4',
    label: '[Desktop] Product 4 image ratio',
    info: 'If set overrides desktop image ratio',
  },
  {
    type: 'text',
    id: 'product_image_mobile_ratio_4',
    label: '[Mobile] Product 4 image ratio',
    info: 'If set overrides mobile image ratio',
  },
  {
    type: 'color',
    id: 'background',
    label: 'Background',
    default: '#f7f8fd',
  },
  {
    type: 'color',
    id: 'text_color',
    label: 'Text color',
    default: '#1e316a',
  },
  {
    type: 'header',
    content: 'Product card layout',
  },
  {
    type: 'checkbox',
    id: 'full_width',
    label: 'Full width',
    info: 'Each product takes 100% width',
    default: false,
  },
  {
    type: 'checkbox',
    id: 'info_inside',
    label: 'Product info inside image',
    info: 'Shows product info at the bottom of the image',
    default: false,
  },
  {
    type: 'text',
    id: 'info_side_padding',
    label: 'Product info left and right padding',
    info: 'Ex: 30px, 45%, 0',
    default: '0',
  },
  {
    type: 'text',
    id: 'info_bottom_padding',
    label: 'Product info bottom padding',
    info: 'Ex: 30px, 45%, 0',
    default: '0',
  },
  {
    type: 'text',
    id: 'mob_info_side_padding',
    label: 'Mobile product info left and right padding',
    info: 'Ex: 30px, 45%, 0',
    default: '0',
  },
  {
    type: 'text',
    id: 'mob_info_bottom_padding',
    label: 'Mobile product info bottom padding',
    info: 'Ex: 30px, 45%, 0',
    default: '0',
  },
];
