module.exports = {
  name: 'Advanced Collection page',
  class: 'shopify-section--main-advanced-collection',
  limit: 1,
  settings: [
    {
      type: 'range',
      id: 'products_per_page',
      label: 'Products per page',
      min: 8,
      max: 50,
      step: 1,
      default: 24,
    },
    {
      type: 'select',
      id: 'pagination_type',
      label: 'Pagination type',
      options: [
        {
          value: 'classic',
          label: 'Classic',
        },
        {
          value: 'infinite',
          label: 'Infinite with button',
        },
        {
          value: 'infinite_scroll',
          label: 'Infinite on scroll',
        },
      ],
      default: 'infinite_scroll',
    },
    {
      type: 'select',
      id: 'grid_layout',
      label: 'Grid layout',
      options: [
        {
          value: 'fixed-3-3/2',
          label: 'Fixed 3-3 / 2',
        },
        {
          value: 'fixed-4-4/2',
          label: 'Fixed 4-4 / 2',
        },
        {
          value: 'alternate-2-4-3/2-2-1-2-2',
          label: 'Alternate 2-4-3 / 2-2-1-2-2',
        },
        {
          value: 'alternate-3-3-2/2-2-2-1-1',
          label: 'Alternate 3-3-2 / 2-2-2-1-1',
        },
        {
          value: 'alternate-4-4-2/2-2-2-2-1-1',
          label: 'Alternate 4-4-2 / 2-2-2-2-1-1',
        },
        {
          value: 'alternate-3-2-4/2-2-1-2-2',
          label: 'Alternate 3-2-4 / 2-2-1-2-2',
        },
      ],
      default: 'fixed-4-4/2',
    },
    {
      type: 'select',
      id: 'mobile_products_per_row',
      label: '[mobile] Products per row',
      info: 'Force to have only one item per line on mobile',
      options: [
        {
          value: 'auto',
          label: 'Auto',
        },
        {
          value: '1',
          label: '1',
        },
      ],
      default: 'auto',
    },
    {
      type: 'header',
      content: 'Container',
    },
    {
      type: 'select',
      id: 'container_size',
      label: 'Container width',
      options: [
        {
          value: 'default',
          label: 'Default',
        },
        {
          value: 'medium',
          label: 'Medium',
        },
        {
          value: 'full-width',
          label: 'Full width',
        },
      ],
      default: 'default',
    },
    {
      type: 'checkbox',
      id: 'override_container_gutter',
      label: 'Override default container gutter',
      default: false,
    },
    {
      type: 'range',
      id: 'desktop_container_gutter',
      label: 'Desktop container gutter',
      min: 0,
      max: 100,
      unit: 'px',
      step: 1,
      default: 40,
    },
    {
      type: 'range',
      id: 'mobile_container_gutter',
      label: 'Mobile container gutter',
      min: 0,
      max: 100,
      unit: 'px',
      step: 1,
      default: 24,
    },
    {
      type: 'header',
      content: 'Product list spacing',
    },
    {
      type: 'checkbox',
      id: 'override_product_list_spacing',
      label: 'Override default spacing',
      default: false,
    },
    {
      type: 'range',
      id: 'desktop_grid_horizontal_gap',
      label: 'Desktop horizontal space',
      min: 0,
      max: 100,
      unit: 'px',
      step: 1,
      default: 24,
    },
    {
      type: 'range',
      id: 'desktop_grid_vertical_gap',
      label: 'Desktop vertical space',
      min: 0,
      max: 100,
      unit: 'px',
      step: 1,
      default: 48,
    },
    {
      type: 'range',
      id: 'mobile_grid_horizontal_gap',
      label: 'Mobile horizontal space',
      min: 0,
      max: 100,
      unit: 'px',
      step: 1,
      default: 12,
    },
    {
      type: 'range',
      id: 'mobile_grid_vertical_gap',
      label: 'Mobile vertical space',
      min: 0,
      max: 100,
      unit: 'px',
      step: 1,
      default: 32,
    },
    {
      type: 'header',
      content: 'Filters',
    },
    {
      type: 'checkbox',
      id: 'show_sort_by',
      label: 'Show sort by',
      default: true,
    },
    {
      type: 'textarea',
      id: 'override_sort_by_options',
      label: "Override 'sort by' options",
      info: 'Available values (one by line) : manual, best-selling, price-ascending, price-descending, title-ascending, title-descending, created-ascending, created-descending',
      default: 'manual\nbest-selling\nprice-ascending\nprice-descending',
    },
    {
      type: 'checkbox',
      id: 'show_filters',
      label: 'Show filters',
      info: '[Customize filters](/admin/menus)',
      default: true,
    },
    {
      type: 'checkbox',
      id: 'show_filter_group_name',
      label: 'Show group name',
      info: 'Group name will be shown inside selected filters.',
      default: false,
    },
    {
      type: 'checkbox',
      id: 'show_available_variants_only',
      label: 'Show only available variants',
      info: 'The results will contain only available variants.',
      default: false,
    },
    {
      type: 'checkbox',
      id: 'hide_empty_filters',
      label: 'Hide filter values without results',
      default: false,
    },
    {
      type: 'checkbox',
      id: 'hide_unique_filters',
      label: 'Hide filters with only one value',
      default: false,
    },
    {
      type: 'checkbox',
      id: 'hide_filter_value_count',
      label: 'Hide number of items in filters values',
      default: false,
    },
    {
      type: 'checkbox',
      id: 'show_color_swatch',
      label: 'Show filter color swatch',
      default: true,
    },
    {
      type: 'select',
      id: 'filter_groups_behavior',
      label: 'Filter groups behavior',
      options: [
        {
          value: 'none',
          label: 'Close all groups by default',
        },
        {
          value: 'first',
          label: 'Open first group by default',
        },
        {
          value: 'all',
          label: 'Open all groups by default',
        },
      ],
      default: 'none',
    },
    {
      type: 'select',
      id: 'filter_position',
      label: 'Position',
      options: [
        {
          value: 'always_visible',
          label: 'Always visible',
        },
        {
          value: 'drawer',
          label: 'Drawer',
        },
      ],
      default: 'drawer',
    },
    {
      type: 'header',
      content: 'Sticky Filter Drawer',
    },
    {
      type: 'checkbox',
      id: 'filter_bar_is_sticky',
      label: 'Sticky Drawer',
      default: true,
    },
    {
      type: 'color',
      id: 'sticky_filter_bar_background',
      label: 'Sticky filter bar background',
      default: 'rgba(0,0,0,0)',
    },
    {
      type: 'color',
      id: 'sticky_filter_bar_text_color',
      label: 'Sticky filter bar text color',
      default: 'rgba(0,0,0,0)',
    },
  ],
  presets: [
    {
      name: '[advanced] Collection page',
    },
  ],
};
