const colors = require('../common/colors.schema');
const sectionLayout = require('../common/sectionLayout.schema');
const promotionBlockBasic = require('../blocks/promotion-block-basic-settings.schema');

module.exports = {
  name: '[Basic] Promotion blocks',
  class: 'shopify-section--promotion-blocks',
  disabled_on: {
    groups: ['header', 'custom.overlay'],
  },
  max_blocks: 12,
  settings: [
    ...sectionLayout(),
    {
      type: 'select',
      id: 'blocks_spacing',
      label: 'Blocks spacing',
      options: [
        {
          value: 'xlarge',
          label: 'XLarge',
        },
        {
          value: 'large',
          label: 'Large',
        },
        {
          value: 'default',
          label: 'Normal',
        },
        {
          value: 'small',
          label: 'Small',
        },
        {
          value: 'xsmall',
          label: 'XSmall',
        },
        {
          value: 'xxsmall',
          label: 'XXSmall',
        },
        {
          value: 'none',
          label: 'None',
        },
      ],
      default: 'default',
    },
    {
      type: 'text',
      id: 'blocks_spacing_custom_desk',
      label: '[Desktop] Blocks spacing',
      info: 'If set overrides desktop spacing',
    },
    {
      type: 'text',
      id: 'blocks_spacing_custom_mobile',
      label: '[Mobile] Blocks spacing',
      info: 'If set overrides mobile spacing',
    },
    {
      type: 'select',
      id: 'section_size',
      label: 'Blocks min height',
      options: [
        {
          value: '',
          label: 'None',
        },
        {
          value: 'small',
          label: 'Small',
        },
        {
          value: 'medium',
          label: 'Medium',
        },
        {
          value: 'large',
          label: 'Large',
        },
      ],
      default: '',
    },
    {
      type: 'select',
      id: 'section_layout',
      label: 'Section layout',
      options: [
        {
          value: 'flex_grid',
          label: 'Flex Grid',
        },
        {
          value: 'grid',
          label: 'Grid',
        },
        {
          value: 'columns',
          label: 'Columns',
        },
      ],
      default: 'flex_grid',
    },
    {
      type: 'range',
      id: 'section_columns_desktop',
      label: 'Columns desktop',
      min: 1,
      max: 12,
      step: 1,
      default: 3,
    },
    {
      type: 'checkbox',
      id: 'stack_on_mobile',
      label: 'Stack on mobile',
      default: true,
    },
    {
      type: 'select',
      id: 'section_columns_mobile',
      label: 'Columns mobile',
      options: [
        {
          value: '1',
          label: '1',
        },
        {
          value: '2',
          label: '2',
        },
      ],
      default: '1',
    },
    {
      type: 'header',
      content: 'Mobile carousel options',
      info: 'Only applied if items are not stacked',
    },
    {
      type: 'checkbox',
      id: 'show_dots_nav',
      label: 'Show dots navigation',
      default: true,
    },
    {
      type: 'select',
      id: 'dots_nav_position',
      label: 'Dots nav position',
      options: [
        {
          value: 'inside',
          label: 'Inside',
        },
        {
          value: 'outside',
          label: 'Outside',
        },
      ],
      default: 'inside',
    },
    {
      type: 'color',
      id: 'dots_nav_color',
      label: 'Dots nav color',
      default: '#FFFFFF',
    },
    {
      type: 'checkbox',
      id: 'carousel_item_fullwidth',
      label: 'Fullwidth carousel item',
      default: true,
    },
    {
      type: 'header',
      content: 'Colors',
    },
    {
      type: 'color',
      id: 'background',
      label: 'Background',
      default: 'rgba(0,0,0,0)',
    },
  ],
  blocks: [
    {
      type: 'media',
      name: 'Media with text',
      settings: [...promotionBlockBasic()],
    },
    {
      type: 'quote',
      name: 'Quote',
      settings: [
        {
          type: 'checkbox',
          id: 'highlight',
          label: 'Highlight tile',
          info: 'A highlighted tile takes bigger space. Only has effect on desktop. Do not highlight more than 1 item per row.',
          default: false,
        },
        {
          type: 'text',
          id: 'subheading',
          label: 'Subheading',
          default: 'Subheading',
        },
        {
          type: 'text',
          id: 'content',
          label: 'Content',
          default: 'Use this text to share information about your brand with your customers.',
        },
        {
          type: 'text',
          id: 'author',
          label: 'Author',
          default: 'John S.',
        },
        {
          type: 'color',
          id: 'background',
          label: 'Background',
          default: '#f7f8fd',
        },
        {
          type: 'color',
          id: 'text_color',
          label: 'Text color',
          default: '#1e316a',
        },
      ],
    },
    {
      type: 'newsletter',
      name: 'Newsletter',
      limit: 1,
      settings: [
        {
          type: 'paragraph',
          content:
            'Customers who subscribe will have their email address added to the "accepts marketing" [customer list](/admin/customers?query=&accepts_marketing=1).',
        },
        {
          type: 'checkbox',
          id: 'highlight',
          label: 'Highlight tile',
          info: 'A highlighted tile takes bigger space. Only has effect on desktop. Do not highlight more than 1 item per row.',
          default: false,
        },
        {
          type: 'text',
          id: 'title',
          label: 'Heading',
          default: 'Join us',
        },
        {
          type: 'richtext',
          id: 'content',
          label: 'Rich text',
          default: '<p>A short sentence describing what someone will receive by subscribing</p>',
        },
        {
          type: 'select',
          id: 'text_position',
          label: 'Text position',
          options: [
            {
              value: 'top_left',
              label: 'Top left',
            },
            {
              value: 'top_center',
              label: 'Top center',
            },
            {
              value: 'top_right',
              label: 'Top right',
            },
            {
              value: 'middle_left',
              label: 'Middle left',
            },
            {
              value: 'middle_center',
              label: 'Middle center',
            },
            {
              value: 'middle_right',
              label: 'Middle right',
            },
            {
              value: 'bottom_left',
              label: 'Bottom left',
            },
            {
              value: 'bottom_center',
              label: 'Bottom center',
            },
            {
              value: 'bottom_right',
              label: 'Bottom right',
            },
          ],
          default: 'middle_center',
        },
        {
          type: 'color',
          id: 'background',
          label: 'Background',
          default: '#f7f8fd',
        },
        {
          type: 'color',
          id: 'text_color',
          label: 'Text color',
          default: '#1e316a',
        },
        {
          type: 'color',
          id: 'button_background',
          label: 'Button background',
          default: '#ffffff',
        },
        {
          type: 'color',
          id: 'button_text_color',
          label: 'Button text color',
          default: '#1e316a',
        },
      ],
    },
    {
      type: 'featured_products',
      name: 'Featured products',
      settings: [
        {
          type: 'checkbox',
          id: 'highlight',
          label: 'Highlight tile',
          info: 'A highlighted tile takes bigger space. Only has effect on desktop. Do not highlight more than 1 item per row.',
          default: false,
        },
        {
          type: 'text',
          id: 'subheading',
          label: 'Subheading',
          default: 'Featured',
        },
        {
          type: 'product',
          id: 'product_1',
          label: 'Product 1',
        },
        {
          type: 'image_picker',
          id: 'product_image_1',
          label: 'Use instead of the product image',
          info: '1800 x 900px .jpg recommended',
        },
        {
          type: 'checkbox',
          id: 'product_full_content_1',
          label: 'Full product content',
          info: 'Full content may include some additional features like hover buttons, size selectors etc.',
          default: false,
        },
        {
          type: 'text',
          id: 'product_image_desk_ratio_1',
          label: '[Desktop] Product 1 image ratio',
          info: 'If set overrides desktop image ratio',
        },
        {
          type: 'text',
          id: 'product_image_mobile_ratio_1',
          label: '[Mobile] Product 1 image ratio',
          info: 'If set overrides mobile image ratio',
        },
        {
          type: 'product',
          id: 'product_2',
          label: 'Product 2',
        },
        {
          type: 'image_picker',
          id: 'product_image_2',
          label: 'Use instead of the product image',
          info: '1800 x 900px .jpg recommended',
        },
        {
          type: 'checkbox',
          id: 'product_full_content_2',
          label: 'Full product content',
          info: 'Full content may include some additional features like hover buttons, size selectors etc.',
          default: false,
        },
        {
          type: 'text',
          id: 'product_image_desk_ratio_2',
          label: '[Desktop] Product 2 image ratio',
          info: 'If set overrides desktop image ratio',
        },
        {
          type: 'text',
          id: 'product_image_mobile_ratio_2',
          label: '[Mobile] Product 2 image ratio',
          info: 'If set overrides mobile image ratio',
        },
        {
          type: 'product',
          id: 'product_3',
          label: 'Product 3',
        },
        {
          type: 'image_picker',
          id: 'product_image_3',
          label: 'Use instead of the product image',
          info: '1800 x 900px .jpg recommended',
        },
        {
          type: 'checkbox',
          id: 'product_full_content_3',
          label: 'Full product content',
          info: 'Full content may include some additional features like hover buttons, size selectors etc.',
          default: false,
        },
        {
          type: 'text',
          id: 'product_image_desk_ratio_3',
          label: '[Desktop] Product 3 image ratio',
          info: 'If set overrides desktop image ratio',
        },
        {
          type: 'text',
          id: 'product_image_mobile_ratio_3',
          label: '[Mobile] Product 3 image ratio',
          info: 'If set overrides mobile image ratio',
        },
        {
          type: 'product',
          id: 'product_4',
          label: 'Product 4',
        },
        {
          type: 'image_picker',
          id: 'product_image_4',
          label: 'Use instead of the product image',
          info: '1800 x 900px .jpg recommended',
        },
        {
          type: 'checkbox',
          id: 'product_full_content_4',
          label: 'Full product content',
          info: 'Full content may include some additional features like hover buttons, size selectors etc.',
          default: false,
        },
        {
          type: 'text',
          id: 'product_image_desk_ratio_4',
          label: '[Desktop] Product 4 image ratio',
          info: 'If set overrides desktop image ratio',
        },
        {
          type: 'text',
          id: 'product_image_mobile_ratio_4',
          label: '[Mobile] Product 4 image ratio',
          info: 'If set overrides mobile image ratio',
        },
        {
          type: 'color',
          id: 'background',
          label: 'Background',
          default: '#f7f8fd',
        },
        {
          type: 'color',
          id: 'text_color',
          label: 'Text color',
          default: '#1e316a',
        },
        {
          type: 'header',
          content: 'Product card layout',
        },
        {
          type: 'checkbox',
          id: 'full_width',
          label: 'Full width',
          info: 'Each product takes 100% width',
          default: false,
        },
        {
          type: 'checkbox',
          id: 'info_inside',
          label: 'Product info inside image',
          info: 'Shows product info at the bottom of the image',
          default: false,
        },
        {
          type: 'text',
          id: 'info_side_padding',
          label: 'Product info left and right padding',
          info: 'Ex: 30px, 45%, 0',
          default: '0',
        },
        {
          type: 'text',
          id: 'info_bottom_padding',
          label: 'Product info bottom padding',
          info: 'Ex: 30px, 45%, 0',
          default: '0',
        },
        {
          type: 'text',
          id: 'mob_info_side_padding',
          label: 'Mobile product info left and right padding',
          info: 'Ex: 30px, 45%, 0',
          default: '0',
        },
        {
          type: 'text',
          id: 'mob_info_bottom_padding',
          label: 'Mobile product info bottom padding',
          info: 'Ex: 30px, 45%, 0',
          default: '0',
        },
      ],
    },
    {
      type: 'look',
      name: 'Look',
      settings: [
        {
          type: 'image_picker',
          id: 'image',
          label: 'Image',
          info: '2160 x 1000px .jpg recommended',
        },
        {
          type: 'image_picker',
          id: 'mobile_image',
          label: 'Mobile image',
          info: '1000 x 800px .jpg recommended. Default image is used if none is selected. To position the hotspots precisely, switch to mobile mode.',
        },
        {
          type: 'select',
          id: 'dot_type',
          label: 'Hotspot style',
          options: [
            {
              value: 'normal',
              label: 'Normal',
            },
            {
              value: 'inverted',
              label: 'Inverted',
            },
          ],
          default: 'normal',
        },
        {
          type: 'select',
          id: 'btn_style',
          label: 'Button style',
          options: [
            {
              label: 'Dot',
              value: 'dot',
            },
            {
              label: 'Plus',
              value: 'plus',
            },
          ],
          default: 'dot',
        },
        {
          type: 'header',
          content: 'Product 1',
        },
        {
          type: 'product',
          id: 'product_1',
          label: 'Product',
        },
        {
          type: 'range',
          id: 'product_1_horizontal_position',
          min: 5,
          max: 95,
          step: 1,
          unit: '%',
          label: 'Horizontal position',
          default: 30,
        },
        {
          type: 'range',
          id: 'product_1_vertical_position',
          min: 5,
          max: 95,
          step: 1,
          unit: '%',
          label: 'Vertical position',
          default: 30,
        },
        {
          type: 'range',
          id: 'product_1_horizontal_position_mobile',
          min: 5,
          max: 95,
          step: 1,
          unit: '%',
          label: 'Horizontal position (mobile image)',
          default: 30,
        },
        {
          type: 'range',
          id: 'product_1_vertical_position_mobile',
          min: 5,
          max: 95,
          step: 1,
          unit: '%',
          label: 'Vertical position (mobile image)',
          default: 30,
        },
        {
          type: 'header',
          content: 'Product 2',
        },
        {
          type: 'product',
          id: 'product_2',
          label: 'Product',
        },
        {
          type: 'range',
          id: 'product_2_horizontal_position',
          min: 5,
          max: 95,
          step: 1,
          unit: '%',
          label: 'Horizontal position',
          default: 50,
        },
        {
          type: 'range',
          id: 'product_2_vertical_position',
          min: 5,
          max: 95,
          step: 1,
          unit: '%',
          label: 'Vertical position',
          default: 50,
        },
        {
          type: 'range',
          id: 'product_2_horizontal_position_mobile',
          min: 5,
          max: 95,
          step: 1,
          unit: '%',
          label: 'Horizontal position (mobile image)',
          default: 50,
        },
        {
          type: 'range',
          id: 'product_2_vertical_position_mobile',
          min: 5,
          max: 95,
          step: 1,
          unit: '%',
          label: 'Vertical position (mobile image)',
          default: 50,
        },
        {
          type: 'header',
          content: 'Product 3',
        },
        {
          type: 'product',
          id: 'product_3',
          label: 'Product',
        },
        {
          type: 'range',
          id: 'product_3_horizontal_position',
          min: 5,
          max: 95,
          step: 1,
          unit: '%',
          label: 'Horizontal position',
          default: 70,
        },
        {
          type: 'range',
          id: 'product_3_vertical_position',
          min: 5,
          max: 95,
          step: 1,
          unit: '%',
          label: 'Vertical position',
          default: 70,
        },
        {
          type: 'range',
          id: 'product_3_horizontal_position_mobile',
          min: 5,
          max: 95,
          step: 1,
          unit: '%',
          label: 'Horizontal position (mobile image)',
          default: 70,
        },
        {
          type: 'range',
          id: 'product_3_vertical_position_mobile',
          min: 5,
          max: 95,
          step: 1,
          unit: '%',
          label: 'Vertical position (mobile image)',
          default: 70,
        },
        {
          type: 'header',
          content: 'Layout',
        },
        {
          type: 'checkbox',
          id: 'highlight',
          label: 'Highlight tile',
          info: 'A highlighted tile takes bigger space.',
          default: false,
        },
        {
          type: 'header',
          content: 'Advanced grid layout',
          info: "Only works with 'grid layout' on the section",
        },
        {
          type: 'range',
          id: 'col_size',
          label: 'Block col size (width)',
          min: 1,
          max: 12,
          step: 1,
          default: 1,
        },
        {
          type: 'range',
          id: 'row_size',
          label: 'Block row size (height)',
          min: 1,
          max: 10,
          step: 1,
          default: 1,
        },
      ],
    },
  ],
  presets: [
    {
      name: '[Basic] Promotion blocks',
      settings: {},
      blocks: [
        {
          type: 'media',
        },
        {
          type: 'media',
        },
        {
          type: 'media',
        },
      ],
    },
  ],
};
