export const countriesCode = [
  { country: 'Australia', prefix: '+61', lang: 'en-au' },
  { country: 'Cyprus', prefix: '+357', lang: 'cy' },
  { country: 'Israel', prefix: '+972', lang: 'he-il' },
  { country: 'South Korea', prefix: '+82', lang: 'kr' },
  { country: 'France', prefix: '+33', lang: 'fr-fr' },
  { country: 'Germany', prefix: '+49', lang: 'de' },
  { country: 'Belgium', prefix: '+32', lang: 'fr-be' },
  { country: 'Spain', prefix: '+34', lang: 'es-es' },
  { country: 'Italy', prefix: '+39', lang: 'it-it' },
  { country: 'Luxembourg', prefix: '+352', lang: 'fr-lu' },
  { country: 'Netherlands', prefix: '+31', lang: 'nl-nl' },
  { country: 'Holy See (Vatican City State)', prefix: '+39' },
  { country: 'Austria', prefix: '+43', lang: 'de-at' },
  { country: 'Denmark', prefix: '+45', lang: 'da-dk' },
  { country: 'Finland', prefix: '+358', lang: 'sv-fi' },
  { country: 'Greece', prefix: '+30', lang: 'el-gr' },
  { country: 'Ireland', prefix: '+353', lang: 'en-ie' },
  { country: 'United Arab Emirates', prefix: '+971', lang: 'ar' },
  { country: 'Portugal', prefix: '+351', lang: 'pt-pt' },
  { country: 'Sweden', prefix: '+46', lang: 'sv-sv' },
  { country: 'Bulgaria', prefix: '+359', lang: 'bg-bg' },
  { country: 'Croatia', prefix: '+385', lang: 'hr-hr' },
  { country: 'Estonia', prefix: '+372', lang: 'et-ee' },
  { country: 'Hungary', prefix: '+36', lang: 'hu-hu' },
  { country: 'Lithuania', prefix: '+370', lang: 'lt-lt' },
  { country: 'Latvia', prefix: '+371', lang: 'lv-lv' },
  { country: 'Poland', prefix: '+48', lang: 'pl-pl' },
  { country: 'Romania', prefix: '+40', lang: 'ro-ro' },
  { country: 'Slovakia', prefix: '+421', lang: 'sk-sk' },
  { country: 'Slovenia', prefix: '+386', lang: 'sl-si' },
  { country: 'Czech Republic', prefix: '+420', lang: 'cz-cz' },
  { country: 'Norway', prefix: '+47', lang: 'nn-no' },
  { country: 'Switzerland', prefix: '+41', lang: 'fr-ch' },
  { country: 'Canada', prefix: '+1', lang: 'fr-ca' },
  { country: 'United Kingdom', prefix: '+44', lang: 'en-en' },
  { country: 'United States', prefix: '+1', lang: 'en-us' },
  { country: 'Japan', prefix: '+81', lang: 'ja-jp' },
  { country: 'Malaysia', prefix: '+60', lang: 'ms-my' },
  { country: 'Malta', prefix: '+356', lang: 'mt-mt' },
  { country: 'New Zealand', prefix: '+64', lang: 'en-nz' },
  { country: 'Hong Kong', prefix: '+852', lang: 'zh-hk' },
  { country: 'Singapore', prefix: '+65', lang: 'zh-sg' },
];
