import headings from '../common/headings.schema';
import colors from '../common/colors.schema';
import sectionLayout from '../common/sectionLayout.schema';

module.exports = {
  name: 'Shop the look',
  class: 'shopify-section--shop-the-look',
  disabled_on: {
    templates: ['password'],
    groups: ['header', 'custom.overlay', 'footer'],
  },
  max_blocks: 6,
  settings: [
    {
      type: 'checkbox',
      id: 'reveal_on_scroll',
      label: 'Reveal on scroll',
      info: 'Show animation when section becomes visible.',
      default: false,
    },
    {
      type: 'text',
      id: 'label',
      label: 'Navigation label',
      default: 'Shop the looks',
      info: 'Shown when multiple looks are featured.',
    },
    ...headings(),
    ...sectionLayout(),
    ...colors(),
  ],
  blocks: [
    {
      type: 'look',
      name: 'Look',
      settings: [
        {
          type: 'image_picker',
          id: 'image',
          label: 'Image',
          info: '2160 x 1000px .jpg recommended',
        },
        {
          type: 'image_picker',
          id: 'mobile_image',
          label: 'Mobile image',
          info: '1000 x 800px .jpg recommended. Default image is used if none is selected. To position the hotspots precisely, switch to mobile mode.',
        },
        {
          type: 'select',
          id: 'dot_type',
          label: 'Hotspot style',
          options: [
            {
              value: 'normal',
              label: 'Normal',
            },
            {
              value: 'inverted',
              label: 'Inverted',
            },
          ],
          default: 'normal',
        },
        {
          type: 'select',
          id: 'btn_style',
          label: 'Button style',
          options: [
            {
              label: 'Dot',
              value: 'dot',
            },
            {
              label: 'Plus',
              value: 'plus',
            },
          ],
          default: 'dot',
        },
        {
          type: 'header',
          content: 'Product 1',
        },
        {
          type: 'product',
          id: 'product_1',
          label: 'Product',
        },
        {
          type: 'range',
          id: 'product_1_horizontal_position',
          min: 5,
          max: 95,
          step: 1,
          unit: '%',
          label: 'Horizontal position',
          default: 30,
        },
        {
          type: 'range',
          id: 'product_1_vertical_position',
          min: 5,
          max: 95,
          step: 1,
          unit: '%',
          label: 'Vertical position',
          default: 30,
        },
        {
          type: 'range',
          id: 'product_1_horizontal_position_mobile',
          min: 5,
          max: 95,
          step: 1,
          unit: '%',
          label: 'Horizontal position (mobile image)',
          default: 30,
        },
        {
          type: 'range',
          id: 'product_1_vertical_position_mobile',
          min: 5,
          max: 95,
          step: 1,
          unit: '%',
          label: 'Vertical position (mobile image)',
          default: 30,
        },
        {
          type: 'header',
          content: 'Product 2',
        },
        {
          type: 'product',
          id: 'product_2',
          label: 'Product',
        },
        {
          type: 'range',
          id: 'product_2_horizontal_position',
          min: 5,
          max: 95,
          step: 1,
          unit: '%',
          label: 'Horizontal position',
          default: 50,
        },
        {
          type: 'range',
          id: 'product_2_vertical_position',
          min: 5,
          max: 95,
          step: 1,
          unit: '%',
          label: 'Vertical position',
          default: 50,
        },
        {
          type: 'range',
          id: 'product_2_horizontal_position_mobile',
          min: 5,
          max: 95,
          step: 1,
          unit: '%',
          label: 'Horizontal position (mobile image)',
          default: 50,
        },
        {
          type: 'range',
          id: 'product_2_vertical_position_mobile',
          min: 5,
          max: 95,
          step: 1,
          unit: '%',
          label: 'Vertical position (mobile image)',
          default: 50,
        },
        {
          type: 'header',
          content: 'Product 3',
        },
        {
          type: 'product',
          id: 'product_3',
          label: 'Product',
        },
        {
          type: 'range',
          id: 'product_3_horizontal_position',
          min: 5,
          max: 95,
          step: 1,
          unit: '%',
          label: 'Horizontal position',
          default: 70,
        },
        {
          type: 'range',
          id: 'product_3_vertical_position',
          min: 5,
          max: 95,
          step: 1,
          unit: '%',
          label: 'Vertical position',
          default: 70,
        },
        {
          type: 'range',
          id: 'product_3_horizontal_position_mobile',
          min: 5,
          max: 95,
          step: 1,
          unit: '%',
          label: 'Horizontal position (mobile image)',
          default: 70,
        },
        {
          type: 'range',
          id: 'product_3_vertical_position_mobile',
          min: 5,
          max: 95,
          step: 1,
          unit: '%',
          label: 'Vertical position (mobile image)',
          default: 70,
        },
      ],
    },
  ],
  presets: [
    {
      name: 'Shop the look',
      blocks: [
        {
          type: 'look',
          settings: {
            dot_type: 'inverted',
            product_1_horizontal_position: 41,
            product_1_vertical_position: 41,
            product_2_horizontal_position: 46,
            product_2_vertical_position: 64,
            product_3_horizontal_position: 62,
            product_3_vertical_position: 50,
          },
        },
      ],
    },
  ],
};
