#!/bin/sh

echo "🚀 Ejecutando lint, prettier y tests con cobertura..."

npx lint-staged
npm test -- --coverage --maxWorkers=2

if [ -f "./sonar-project.js" ]; then
  echo "📡 Enviando resultados a SonarQube..."
  node sonar-project.js
fi
